version: '3.3'

services:
    algoritmeregister-api:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8081 -t public
        environment:
            docker: "true"
        ports:
            - 8081:8081
        volumes:
            - .:/var/www
